import reflex as rx
from BlackboardLM.state import AppState

_PRESET_CHIPS = [
    {"key": "summarize", "label": "Summary"},
    {"key": "study_guide", "label": "Study Guide"},
    {"key": "faq", "label": "FAQ"},
    {"key": "briefing", "label": "Briefing"},
    {"key": "timeline", "label": "Timeline"},
    {"key": "key_concepts", "label": "Concepts"},
    {"key": "critique", "label": "Critique"},
    {"key": "deep_dive", "label": "Deep Dive"},
]

def input_bar() -> rx.Component:
    return rx.fragment(
        rx.hstack(
            rx.text(
                rx.cond(AppState.presets_expanded, "Presets ▾", "Presets ▸"),
                font_size="12px",
                color=AppState.theme["text_muted"],
                cursor="pointer",
                white_space="nowrap",
                on_click=AppState.toggle_presets,
                style={"_hover": {"color": AppState.theme["primary"]}},
                transition="color 0.15s ease",
            ),
            width="100%",
            justify="center",
            padding_bottom="2px",
        ),
        rx.box(
            rx.hstack(
                rx.foreach(
                    _PRESET_CHIPS,
                    lambda _chip: rx.box(
                        rx.text(
                            _chip["label"],
                            font_size="12px",
                            white_space="nowrap",
                        ),
                        padding="1px 8px",
                        border_radius="full",
                        cursor="pointer",
                        background=rx.cond(
                            AppState.selected_preset == _chip["key"],
                            AppState.theme["primary"],
                            "transparent",
                        ),
                        color=rx.cond(
                            AppState.selected_preset == _chip["key"],
                            AppState.theme["background"],
                            AppState.theme["text_muted"],
                        ),
                        border=f"1px solid {rx.cond(AppState.selected_preset == _chip["key"], AppState.theme["primary"], AppState.theme["text_muted"])}",
                        on_click=AppState.set_preset(_chip["key"]),
                        style={"_hover": {"border_color": AppState.theme["primary"]}},
                        transition="all 0.15s ease",
                    ),
                ),
                spacing="1",
                flex_wrap="wrap",
                justify="center",
            ),
            max_height=rx.cond(AppState.presets_expanded, "60px", "0px"),
            overflow="hidden",
            padding_bottom=rx.cond(AppState.presets_expanded, "6px", "0px"),
            style={"transition": "max-height 0.3s ease, padding 0.3s ease"},
        ),
        rx.box(
            rx.form(
                rx.hstack(
                    rx.icon("feather", size=18, color=AppState.theme["text_muted"], flex_shrink="0"),
                    rx.text_area(
                        value=AppState.current_input,
                        on_change=AppState.set_input,
                        placeholder=AppState.theme["placeholder"],
                        width="100%",
                        variant="soft",
                        font_family=AppState.theme["font_body"],
                        font_style="italic",
                        font_size="16px",
                        color=AppState.theme["text_primary"],
                        rows="1",
                        resize="none",
                        style={
                            "background": "transparent",
                            "border": "none",
                            "box_shadow": "none",
                            "outline": "none",
                            "padding": "8px 4px",
                            "line_height": "24px",
                            "min_height": "24px",
                            "overflow": "hidden",
                        },
                        color_scheme="gold",
                    ),
                    rx.button(
                        rx.cond(
                            AppState.is_processing,
                            rx.spinner(size="3", color=AppState.theme["background"]),
                            rx.icon("send-horizontal", size=18),
                        ),
                        type="submit",
                        background=AppState.theme["primary"],
                        color=AppState.theme["background"],
                        border_radius="full",
                        padding="8px",
                        cursor="pointer",
                        flex_shrink="0",
                        style={"_hover": {"box_shadow": f"0 0 15px {AppState.theme["primary"]}"}},
                    ),
                    spacing="2",
                    width="100%",
                    align="center",
                ),
                on_submit=AppState.send_message,
                width="100%",
                reset_on_submit=False,
            ),
            border_radius="16px",
            background=AppState.theme["input_bg"],
            border=AppState.theme["input_border"],
            box_shadow=AppState.theme["shadow"],
            padding="10px 20px",
            margin="0",
            width="100%",
            class_name="input-container",
        ),
    )
